### PR TITLE
Undo revert of refactored code

### PR DESCRIPTION
**Pull request by johnhaley81**

### CODE REVIEW

**Comment by tbranyen** [comment]
Should I merge this?

**Comment by johnhaley81** [comment]
I think so. We should do a version bump of this library as well. I don't want something unexpectedly breaking in nodegit.

**Comment by johnhaley81** [comment]
I'm merging this and then I'll update nodegit accordingly. We should major version bump since I had to change to the latest nodegit-promise as well.

**Comment by johnhaley81** [comment]
So we'll need better tests for this library. Apparently this is breaking a lot of stuff not even related to nodegit. I'm reverting this for now.

**Pull request merged**
