### PR TITLE
Fix issue with async functions being cached as-is, and so not getting…

### LINKED ISSUE #13: promisified functions are cached in an 'unpromisified' state
The cache currently puts the original function in it, so when the function is seen again, instead of being promisified, the original is returned instead.

e.g.
```js
var a = { a: function(cb) { /*...*/ cb(); } };
a.b = a.a;
promisify(a);
a.b().then(/*...*/); // ERROR: Cannot call 'then' on undefined.
```

### PR DESCRIPTION
**Pull request by jon-hall**
… wrapped if they are encountered elsewhere in the object being promisified.

Fixes #13.

### CODE REVIEW

**Comment by maxkorp** [comment]
Seems like the test errors on this were just network glitches on travis, starting those over again :+1:

**Comment by maxkorp** [comment]
Ah, so, it's a module install failure against node 0.8, so pending hearing back from other maintainers re: dropping 0.8 support (its a weeee bit out of date at this point), this should be good to merge :+1:

**Comment by maxkorp** [comment]
Can you rebase this on top of master please, to get the updated version matrix (it doesnt appear there were any other changes, so a rebase should be safe).

**Comment by jon-hall** [comment]
Cheers for updating the test config so quickly :smiley:, rebased and pushed and it looks like everything passes now.

**Comment by maxkorp** [comment]
Shoop da woop!

**Pull request merged**
